import type { MetadataRoute } from "next";

import { site } from "@/data/site";

/**
 * Sitemap: one entry per primary route.
 *
 * Build 08 removed the blanket `new Date()` that stamped every URL with the
 * current time on each request. Dates now come from the hand-maintained
 * content revision dates in src/data/site.ts — stable between requests,
 * updated when a route's content actually changes, and never fabricated.
 *
 * Future case-study routes can be generated by mapping the projects data
 * array into this same structure.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  // Sitemap entries must be absolute URLs. With no configured origin the only
  // available origin is the local development fallback, so publish no entries.
  if (!site.urlIsConfigured) return [];

  const updated = (path: keyof typeof site.contentUpdated) =>
    new Date(site.contentUpdated[path]);

  return [
    {
      url: `${site.url}/`,
      lastModified: updated("/"),
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${site.url}/solutions`,
      lastModified: updated("/solutions"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${site.url}/work`,
      lastModified: updated("/work"),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${site.url}/about`,
      lastModified: updated("/about"),
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: `${site.url}/contact`,
      lastModified: updated("/contact"),
      changeFrequency: "yearly",
      priority: 0.7,
    },
  ];
}
